### ISSUE TITLE
Address of 'Dimmer' is sending command to multiple Relais/Dimmers

### ISSUE THREAD

**Issue by VNDCK** [Tiemooowh/homeassistant-teletask#1]
Hi Timothy,

I started using your Teletask Home Assistant integration. GREAT, finally a way to create a modern application to manage my house. I do have some questions though - I hope you don't mind. 

1. I'm adding my Relais/Dimmers as stated in the how-to. However, I have multiple interfaces in my Teletask set-up. Because of this, multiple outputs have the same "address". Am I doing something wrong, or is this just not implemented yet? 

  light:
  - doip_component: relay
    address: "1"
    brightness_address: "1"
    name: "Indirect_Leefruimte"

  - doip_component: relay
    address: "1"
    name: "Spots_Leefruimte"

2. When using a slider to manage my dimmers, they won't go completely out - the minimum is 1%. Also, when adding a button to my slider to "Power Off", nothing happens. 
3. Is there a way to get the temperature from the TDS12026 TOUCH interfaces?

Thank you!! Great work.

**Comment by Tiemooowh** [comment]
hey VNDCK,

1. Just making sure I understand the issue:
The Spots and Indirect lightning are tied to the same relay on the Teletask relay? 
My (personal) insights / experience.
- I always keep them seperated, so the on and off for spots don't mix with theh indirect lightning, so from a hardware point of view, I'd split them over 2 relays with different addresses.
- If spliting them up ain't an option, you can tie the indirect lightning to a Flag instead of to a Relay

2. Splitting them up will also resolve your second point, since you have one for the on/off (the relay) and one for the dimming capabilities

3. At this point, I haven't implemented it yet (I do have the same interfaces here, but wanted to first get the minimum viable product out ;-))

Thanks for the compliments, much appreciated!

T

**Comment by VNDCK** [comment]
Hey Timothy!

My dimmable lights are on a seperate Relay interface, TDS13512. When I go to 'Diagnose' in Prosoft, I see that the addresses on the extra relay overlap with the addresses on my main unit. Do you mean this? 

![image](https://user-images.githubusercontent.com/39057307/133934224-52a6e79d-946d-43a5-8e27-5b8dffa8dedf.png)
![image](https://user-images.githubusercontent.com/39057307/133934233-4c318ff0-274c-4832-be74-167b980d1904.png)

Do you have an example on how to do this with flags? Never worked with them.

Thank you very much!

**Comment by Tiemooowh** [comment]
feedback sent by mail
